export { tableToSamples }                                 from './src/tableToSamples'
export { samplesToTable, samplesToTabular }               from './src/samplesToTable'
export { toTable }                                        from './src/tabularToTable'
export { samplesToCrostab }                               from './src/samplesToCrostab'
export { groupedToSurject }                               from './src/groupedToSurject'
export { surjectToGrouped }                               from './src/surjectToGrouped'
export { crostabToNested }                                from './src/crostabToNested'
export { nestedToTable }                                  from './src/nestedToTable'
export { tableToNested }                                  from './src/tableToNested'
export { crostabToTable, tableToMatrix, crostabToMatrix } from './src/specialization'